version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: democary
      POSTGRES_USER: democracy_bot
      POSTGRES_PASSWORD: my_super_secret_password_please_change_me
    expose:
      - "5432"
    volumes:
      - database_storage:/var/lib/postgresql/data
  bot:
    build: .
    restart: always
    depends_on:
      - db
    links:
      - db:postgres
    environment:
      BOT_TOKEN: 123456:YourBotTokenGoesHere
      DB_USER: democracy_bot
      DB_NAME: democary
      DB_PASS: my_super_secret_password_please_change_me
      DB_SERVICE: postgres
      DB_PORT: 5432
    command: python -u bot.py

volumes:
  database_storage: {}